[package]
name = "commands"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }

poise.workspace = true
serenity.workspace = true
songbird.workspace = true
tracing.workspace = true

