[package]
name = "commands"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
youtube_dl = "0.9.0"
reqwest = "0.12.20"

poise.workspace = true
serenity.workspace = true
songbird.workspace = true
tracing.workspace = true

